permissions: {}

on:
  push:
  pull_request:

jobs:

  "unit-tests":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go test $(go list ./... | grep -v pkg/controller) -coverprofile cover.out

  "build":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: make build

  "e2e-tests":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: make e2e
        env:
          GOPATH: "${{ runner.temp }}/go"
